[package]
name = "wbtech-l1"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version ="1.40.0", features = ["signal", "rt", "rt-multi-thread", "macros", "time", "sync"] }
flume = "0.11.0"
tokio-util = "0.7.12"
dashmap = "6.1.0"